FILE_BEFORE_STORAGE_MIGRATION = "file-before-storage-migration"
CONTENT = "some-content"
WINDOWS_TEST_DIRECTORY_PATH = r"C:\Users\TestFolder"
WINDOWS_FILE_BEFORE_STORAGE_MIGRATION = f"{FILE_BEFORE_STORAGE_MIGRATION}.txt"
WINDOWS_FILE_WITH_PATH = f"{WINDOWS_TEST_DIRECTORY_PATH}\\{WINDOWS_FILE_BEFORE_STORAGE_MIGRATION}"

NUM_HOTPLUG_DISKS = 3
HOTPLUGGED_DEVICES = [f"/dev/sd{chr(ord('a') + idx)}" for idx in range(NUM_HOTPLUG_DISKS)]
MOUNT_HOTPLUGGED_DEVICE_PATHS = [f"/mnt/hotplug-{idx}" for idx in range(NUM_HOTPLUG_DISKS)]
