FILE_BEFORE_STORAGE_MIGRATION = "file-before-storage-migration"
CONTENT = "some-content"
WINDOWS_TEST_DIRECTORY_PATH = r"C:\Users\TestFolder"
WINDOWS_FILE_BEFORE_STORAGE_MIGRATION = f"{FILE_BEFORE_STORAGE_MIGRATION}.txt"
WINDOWS_FILE_WITH_PATH = f"{WINDOWS_TEST_DIRECTORY_PATH}\\{WINDOWS_FILE_BEFORE_STORAGE_MIGRATION}"

HOTPLUGGED_DEVICE = "/dev/sda"
MOUNT_HOTPLUGGED_DEVICE_PATH = "/mnt/hotplug"
