name: Cherry-pick to cnv-4.99 on Main Merge

on:
  push:
    branches:
      - main

jobs:
  cherry-pick-to-4-99:
    permissions:
      actions: write
      contents: write
      pull-requests: write # Required for creating PRs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          # Fetch all history for cherry-picking
          fetch-depth: 0

      - name: Configure Git
        # Configure Git user for commits made directly in the workflow
        run: |
          git config user.name "${{ secrets.GH_BOT_USERNAME }}"
          git config user.email "${{ secrets.GH_BOT_EMAIL }}"

      - name: Get latest commit from main
        id: get_latest_commit
        run: |
          LATEST_COMMIT_SHA=$(git rev-parse HEAD)
          echo "Latest commit on main: $LATEST_COMMIT_SHA"

          # If the latest commit is a merge, keep its 1st parent as mainline
          if [ "$(git rev-list --parents -n1 "$LATEST_COMMIT_SHA" | wc -w)" -gt 2 ]; then
            echo "note: $LATEST_COMMIT_SHA is a merge commit – will cherry-pick with -m 1"
            echo "mainline_parent=1" >> "$GITHUB_OUTPUT"
          else
            echo "mainline_parent=" >> "$GITHUB_OUTPUT"
          fi
          echo "commit_sha=$LATEST_COMMIT_SHA" >> "$GITHUB_OUTPUT"

          # Safely set the commit message output, which may contain quotes or other special characters.
          # We use the heredoc syntax for GITHUB_OUTPUT, which is the most robust method.
          COMMIT_MESSAGE=$(git log -1 --format=%s "$LATEST_COMMIT_SHA")
          DELIMITER=$(openssl rand -hex 16)
          {
            echo "commit_message<<$DELIMITER"
            echo "$COMMIT_MESSAGE"
            echo "$DELIMITER"
          } >> "$GITHUB_OUTPUT"

          # Safely set the commit body output using a random delimiter.
          DELIMITER=$(openssl rand -hex 16)
          {
            echo "commit_body<<$DELIMITER"
            git log -1 --format=%b "$LATEST_COMMIT_SHA"
            echo "$DELIMITER"
          } >> "$GITHUB_OUTPUT"

      - name: Attempt Cherry-pick and Prepare Branch
        id: prepare_branch
        run: |
          TARGET_BRANCH="cnv-4.99"
          COMMIT_SHA="${{ steps.get_latest_commit.outputs.commit_sha }}"
          COMMIT_MESSAGE_SHORT="${{ steps.get_latest_commit.outputs.commit_message }}"
          TEMP_BRANCH_NAME="cherry-pick-auto/${{ github.event.after }}-${{ github.run_id }}"
          STATUS="no_change" # Default status

          echo "Attempting to cherry-pick $COMMIT_SHA to $TARGET_BRANCH on temporary branch $TEMP_BRANCH_NAME"

          # Fetch the target branch to ensure it's up-to-date locally
          git fetch origin $TARGET_BRANCH

          # Create and switch to the new temporary branch from the target branch
          git checkout -b "$TEMP_BRANCH_NAME" "origin/$TARGET_BRANCH"

          # Prepare cherry-pick options
          MAINLINE_OPT=""
          if [[ -n "${{ steps.get_latest_commit.outputs.mainline_parent }}" ]]; then
            MAINLINE_OPT="-m ${{ steps.get_latest_commit.outputs.mainline_parent }}"
          fi

          # Attempt to cherry-pick the commit. We use --no-commit to inspect the result.
          if git cherry-pick $MAINLINE_OPT --no-commit --keep-redundant-commits "$COMMIT_SHA"; then
            # Cherry-pick command succeeded. Now check if there are actual changes.
            # `git diff --cached --quiet` exits with 1 if there are staged changes, 0 otherwise.
            if ! git diff --cached --quiet; then
              echo "Cherry-pick applied successfully with changes. Committing."
              git commit -m "Cherry-pick: $COMMIT_MESSAGE_SHORT (from $COMMIT_SHA)"
              STATUS="success"
            else
              echo "Cherry-pick was successful but resulted in no changes. The commit may already be on the target branch."
              STATUS="no_change"
            fi
          else
            # Cherry-pick command failed, indicating a conflict.
            echo "Cherry-pick resulted in conflicts. Committing conflicted state for manual resolution."
            git add .
            git commit -m "Cherry-pick Conflicts: $COMMIT_MESSAGE_SHORT (from $COMMIT_SHA)"
            STATUS="conflicted"
          fi

          echo "Final status: $STATUS"
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"

          # Only push the branch and set the output if a PR needs to be created.
          if [[ "$STATUS" == "success" || "$STATUS" == "conflicted" ]]; then
            echo "Pushing temporary branch $TEMP_BRANCH_NAME to origin."
            git push origin "$TEMP_BRANCH_NAME"
            echo "temp_branch_name=$TEMP_BRANCH_NAME" >> "$GITHUB_OUTPUT"
          else
            echo "No PR will be created as there are no changes."
          fi

      - name: Create Pull Request for Successful Cherry-pick
        if: steps.prepare_branch.outputs.status == 'success'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: "Auto Cherry-pick: ${{ steps.get_latest_commit.outputs.commit_message }}"
          body: |
            ## Automated Cherry-pick

            This Pull Request contains the automatically cherry-picked commit:
            `${{ steps.get_latest_commit.outputs.commit_sha }}`
            "${{ steps.get_latest_commit.outputs.commit_message }}"

            The cherry-pick was applied cleanly to `cnv-4.99`. Please review and merge.

            **Original Commit:** ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.get_latest_commit.outputs.commit_sha }}
            ---
            ${{ steps.get_latest_commit.outputs.commit_body }}
          branch: ${{ steps.prepare_branch.outputs.temp_branch_name }}
          base: "cnv-4.99"
          delete-branch: true

      - name: Create Pull Request for Conflicted Cherry-pick
        if: steps.prepare_branch.outputs.status == 'conflicted'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: "Cherry-pick Conflicts: ${{ steps.get_latest_commit.outputs.commit_message }}"
          body: |
            ## Cherry-pick Failed - Manual Intervention Required

            The automatic cherry-pick of commit `${{ steps.get_latest_commit.outputs.commit_sha }}`
            "${{ steps.get_latest_commit.outputs.commit_message }}" from `main` to `cnv-4.99` has resulted in conflicts.

            This Pull Request has been created with the conflicted state. Please resolve the conflicts
            and merge this PR into `cnv-4.99`.

            **Original Commit:** ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.get_latest_commit.outputs.commit_sha }}
            ---
            ${{ steps.get_latest_commit.outputs.commit_body }}
          branch: ${{ steps.prepare_branch.outputs.temp_branch_name }}
          base: "cnv-4.99"
          delete-branch: true
